[package]
name = "bootstrap-admin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
auth = { path = "../auth" }
chrono.workspace = true
dotenvy.workspace = true
entity = { path = "../db/entity" }
sea-orm.workspace = true
tokio.workspace = true
uuid.workspace = true
