//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod categories;
pub mod permissions;
pub mod products;
pub mod role_permissions;
pub mod roles;
pub mod sea_orm_active_enums;
pub mod suppliers;
pub mod users;
