//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "permissions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i16,
    #[sea_orm(unique)]
    pub code: String,
    pub description: String,
    #[sea_orm(has_many, via = "role_permissions")]
    pub roles: HasMany<super::roles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
