//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::categories::Entity as Categories;
pub use super::permissions::Entity as Permissions;
pub use super::products::Entity as Products;
pub use super::role_permissions::Entity as RolePermissions;
pub use super::roles::Entity as Roles;
pub use super::suppliers::Entity as Suppliers;
pub use super::users::Entity as Users;
