//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::CatalogStatus;
use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "products")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub public_id: Uuid,
    #[sea_orm(ignore, column_type = "custom(\"citext\")", select_as = "text", unique)]
    pub sku: String,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub brand: Option<String>,
    pub category_id: i32,
    pub supplier_id: Option<i32>,
    pub unit: String,
    #[sea_orm(column_type = "Decimal(Some((12, 2)))")]
    pub price: Decimal,
    pub status: CatalogStatus,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "category_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub categories: BelongsTo<super::categories::Entity>,
    #[sea_orm(
        belongs_to,
        from = "supplier_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub suppliers: BelongsTo<Option<super::suppliers::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
