//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "roles")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i16,
    #[sea_orm(unique)]
    pub code: String,
    pub name: String,
    pub is_active: bool,
    #[sea_orm(has_many)]
    pub users: HasMany<super::users::Entity>,
    #[sea_orm(has_many, via = "role_permissions")]
    pub permissions: HasMany<super::permissions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
