//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub public_id: Uuid,
    pub role_id: i16,
    #[sea_orm(unique_key = "uq_users_entra_identity")]
    pub entra_tenant_id: Uuid,
    #[sea_orm(unique_key = "uq_users_entra_identity")]
    pub entra_object_id: Uuid,
    pub email: Option<String>,
    pub full_name: Option<String>,
    pub is_active: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "role_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Restrict"
    )]
    pub roles: BelongsTo<super::roles::Entity>,
    #[sea_orm(has_many)]
    pub sessions: HasMany<super::sessions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
